<?php

return [
    [
        'Field' => 'id_logtransmissaoarquivo',
        'Type' => 'int(11) unsigned',
        'Null' => 'NO',
        'Key' => 'PRI',
        'Default' => 'null',
        'Extra' => 'auto_increment',
    ],
    [
        'Field' => 'id_usuarioLogado',
        'Type' => 'int(11) unsigned',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'id_siscliente',
        'Type' => 'int(11)',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'operacao',
        'Type' => 'varchar(45)',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'dataInicio',
        'Type' => 'datetime',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'dataFim',
        'Type' => 'datetime',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'tempoTransacao',
        'Type' => 'varchar(45)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'classe',
        'Type' => 'varchar(255)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'mensagem',
        'Type' => 'longtext',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'conteudo',
        'Type' => 'longtext',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'ipUsuario',
        'Type' => 'varchar(45)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'browser',
        'Type' => 'varchar(255)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'sistemaOperacional',
        'Type' => 'varchar(255)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'nomeArquivo',
        'Type' => 'varchar(45)',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'nomeArquivoXml',
        'Type' => 'varchar(45)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'nomeArquivoAssinado',
        'Type' => 'varchar(45)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'pathCompleto',
        'Type' => 'text',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'pathCompletoXml',
        'Type' => 'text',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'pathCompletoAssinado',
        'Type' => 'text',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'cancelado',
        'Type' => 'tinyint(1)',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'erro',
        'Type' => 'tinyint(1)',
        'Null' => 'YES',
        'Key' => 'MUL',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'excecao',
        'Type' => 'tinyint(1)',
        'Null' => 'YES',
        'Key' => '',
        'Default' => 'null',
        'Extra' => '',
    ],
    [
        'Field' => 'excluido',
        'Type' => 'tinyint(1)',
        'Null' => 'NO',
        'Key' => '',
        'Default' => 0,
        'Extra' => '',
    ],
];